from __future__ import annotations
import logging
import numpy as np
import cv2

from ..config import get_settings
from ..errors import (
    InvalidImageError,
    NoFaceDetectedError,
    MultipleFacesError,
    EmbeddingError,
    ComparisonError,
)
from .models import FaceEmbedding, DetectedFace, FaceDetectionResult

logger = logging.getLogger(__name__)


class FaceEngine:
    """
    Face recognition engine using InsightFace.
    
    Provides:
    - Face detection
    - Face embedding generation
    - Face comparison (cosine similarity)
    """
    
    def __init__(self, settings=None):
        self._settings = settings or get_settings()
        self._app = None
        self._initialized = False
    
    def _initialize(self) -> None:
        """Lazy initialization of InsightFace."""
        if self._initialized:
            return
        
        try:
            import insightface
            self._app = insightface.app.FaceAnalysis(
                name=self._settings.face_model_name,
                providers=['CPUExecutionProvider'] if self._settings.face_ctx_id < 0 else ['CUDAExecutionProvider']
            )
            self._app.prepare(
                ctx_id=self._settings.face_ctx_id,
                det_size=self._settings.face_det_size
            )
            self._initialized = True
            logger.info(f"FaceEngine initialized with model: {self._settings.face_model_name}")
        except ImportError as e:
            raise EmbeddingError(f"InsightFace not installed: {e}")
        except Exception as e:
            raise EmbeddingError(f"Failed to initialize FaceEngine: {e}")
    
    def _decode_image(self, image_bytes: bytes) -> np.ndarray:
        """Decode image bytes to OpenCV image."""
        nparr = np.frombuffer(image_bytes, np.uint8)
        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        if img is None:
            raise InvalidImageError("Failed to decode image: not a valid image format")
        return img
    
    def detect_faces(self, image_bytes: bytes) -> FaceDetectionResult:
        """
        Detect faces in an image.
        
        Args:
            image_bytes: Raw image bytes
            
        Returns:
            FaceDetectionResult with detected faces
            
        Raises:
            InvalidImageError: If image cannot be decoded
        """
        self._initialize()
        img = self._decode_image(image_bytes)
        height, width = img.shape[:2]
        
        faces = self._app.get(img)
        
        detected = []
        for face in faces:
            if face.det_score < self._settings.face_det_thresh:
                continue
            
            bbox = face.bbox.astype(int)
            detected.append(DetectedFace(
                bbox=(int(bbox[0]), int(bbox[1]), int(bbox[2]), int(bbox[3])),
                confidence=float(face.det_score),
                landmark=face.kps.astype(float) if face.kps is not None else None
            ))
        
        return FaceDetectionResult(
            faces=tuple(detected),
            image_width=width,
            image_height=height
        )
    
    def get_embedding(self, image_bytes: bytes) -> FaceEmbedding:
        """
        Generate face embedding from an image.
        
        Assumes single face policy - raises if 0 or multiple faces detected.
        
        Args:
            image_bytes: Raw image bytes
            
        Returns:
            FaceEmbedding with normalized vector
            
        Raises:
            InvalidImageError: If image cannot be decoded
            NoFaceDetectedError: If no face detected
            MultipleFacesError: If multiple faces detected
            EmbeddingError: If embedding generation fails
        """
        self._initialize()
        img = self._decode_image(image_bytes)
        
        faces = self._app.get(img)
        
        # Filter by detection threshold
        valid_faces = [f for f in faces if f.det_score >= self._settings.face_det_thresh]
        
        if not valid_faces:
            raise NoFaceDetectedError("No face detected in image")
        
        if len(valid_faces) > 1:
            raise MultipleFacesError(f"Multiple faces detected ({len(valid_faces)}), expected exactly one")
        
        face = valid_faces[0]
        
        if face.embedding is None:
            raise EmbeddingError("Face embedding not generated by model")
        
        # Normalize embedding
        embedding = face.embedding.astype(np.float32)
        norm = np.linalg.norm(embedding)
        if norm > 0:
            embedding = embedding / norm
        
        return FaceEmbedding(
            vector=embedding,
            dimension=embedding.shape[0],
            normalized=True
        )
    
    def compare(self, embedding1: FaceEmbedding, embedding2: FaceEmbedding) -> float:
        """
        Compare two face embeddings using cosine similarity.
        
        Args:
            embedding1: First face embedding
            embedding2: Second face embedding
            
        Returns:
            Cosine similarity score in range [-1, 1], typically [0, 1] for normalized embeddings
            
        Raises:
            ComparisonError: If embeddings are incompatible
        """
        if embedding1.dimension != embedding2.dimension:
            raise ComparisonError(
                f"Embedding dimension mismatch: {embedding1.dimension} vs {embedding2.dimension}"
            )
        
        # Both embeddings should already be normalized
        v1 = embedding1.vector
        v2 = embedding2.vector
        
        # Cosine similarity
        similarity = float(np.dot(v1, v2))
        
        # Clamp to valid range due to floating point precision
        return max(-1.0, min(1.0, similarity))
    
    def is_match(self, similarity: float) -> bool:
        """
        Determine if similarity score indicates a match.
        
        Uses >= threshold as the decision boundary.
        """
        return similarity >= self._settings.face_match_threshold
    
    @property
    def threshold(self) -> float:
        """Get the current match threshold."""
        return self._settings.face_match_threshold
    
    @property
    def embedding_dimension(self) -> int:
        """Get the embedding dimension (initialized lazily)."""
        if not self._initialized:
            self._initialize()
        # Buffulo_L models typically output 512-dim embeddings
        return 512