from .config import get_settings, reload_settings, Settings
from .errors import (
    FaceError,
    InvalidImageError,
    NoFaceDetectedError,
    MultipleFacesError,
    EmbeddingError,
    ComparisonError,
    SearchError,
    SearchProviderError,
    NoResultsError,
    CandidateError,
    CandidateRetrievalError,
    InvalidCandidateURLError,
    SSRFProtectionError,
    CandidateImageTooLargeError,
    CandidateImageInvalidError,
    CandidateNoFaceError,
    CandidateMultipleFacesError,
    CandidateEmbeddingError,
    EvaluationError,
    NoEvaluatableCandidatesError,
    NoMatchError,
)
from .face import FaceEngine, FaceEmbedding, DetectedFace, FaceDetectionResult
from .search import (
    SearchCandidate,
    SearchResult,
    SearchProviderType,
    SearchProvider,
    SearchProviderFactory,
    MockSearchProvider,
)
from .verification import (
    CandidateImageRetriever,
    CandidateEvaluator,
    CandidateMatch,
    EvaluationStatus,
    CandidateRanker,
    RankedCandidate,
    RankingResult,
    VerificationPipeline,
    VerificationResult,
    create_pipeline,
)

__version__ = "0.3.0"

__all__ = [
    # Config
    "get_settings",
    "reload_settings",
    "Settings",
    # Errors
    "FaceError",
    "InvalidImageError",
    "NoFaceDetectedError",
    "MultipleFacesError",
    "EmbeddingError",
    "ComparisonError",
    "SearchError",
    "SearchProviderError",
    "NoResultsError",
    "CandidateError",
    "CandidateRetrievalError",
    "InvalidCandidateURLError",
    "SSRFProtectionError",
    "CandidateImageTooLargeError",
    "CandidateImageInvalidError",
    "CandidateNoFaceError",
    "CandidateMultipleFacesError",
    "CandidateEmbeddingError",
    "EvaluationError",
    "NoEvaluatableCandidatesError",
    "NoMatchError",
    # Face (Phase 1)
    "FaceEngine",
    "FaceEmbedding",
    "DetectedFace",
    "FaceDetectionResult",
    # Search (Phase 2)
    "SearchCandidate",
    "SearchResult",
    "SearchProviderType",
    "SearchProvider",
    "SearchProviderFactory",
    "MockSearchProvider",
    # Verification (Phase 3)
    "CandidateImageRetriever",
    "CandidateEvaluator",
    "CandidateMatch",
    "EvaluationStatus",
    "CandidateRanker",
    "RankedCandidate",
    "RankingResult",
    "VerificationPipeline",
    "VerificationResult",
    "create_pipeline",
]